### ISSUE TITLE
How to use this tool

### ISSUE THREAD

**Issue by liukun4515** [DistributedClocks/JVector#5]
I want to use this tool in the distributed system [Cassandra](https://github.com/apache/cassandra).
Should I modify the source code in the Cassandra or not?
If not, what should I do to use this tool in this system?

**Comment by bestchai** [comment]
Yes, you have to modify the system source code. In particular, you must wrap message buffers using our API. That is, you'll need to find places where Cassandra sends and receives messages, and instrument those locations manually. The example in the project README shows you how to do this, along with an API that you can use. Try following that and let us know if you have any specific questions on the usage.
